{{- if .Values.istio.enabled }}
{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  host: {{ include "backend.fullname" . }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
  subsets:
    - name: v1
      labels:
        version: {{ .Chart.AppVersion | quote }}
{{- end }}
{{- end }}
