apiVersion: v2
name: ansible-template-frontend
description: Helm chart for Ansible Template Frontend React Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - react
  - frontend
  - nginx
  - ansible
maintainers:
  - name: gunampalli
    email: gunampalli@example.com
